### ISSUE TITLE
Should we still use this project?

### ISSUE THREAD

**Issue by mitar** [openwisp/netengine#43]
We are looking into a SNMP AirOS data collecting in Python, should we use this library? Is it still in development?

**Comment by nemesisdesign** [comment]
Hi @mitar, this is the project that triggered me to work on NetJSON, but since then I paused the work on this library because I had other priorities, so this project has been unmantained for some time.

The interesting thing is that I will need to resume the work on this library, complete it and change the format so that is compatible with `NetJSON DeviceMonitoring` in the second half of 2016.

So should you use this library? It depends on what you want.. if you need something simple, and you need it right now, you should probably use a home-baked solution. If you would like to have a good abstraction layer, in this library we have done some work; it surely needs to be improved, but it's not like starting from zero.

**Comment by mitar** [comment]
So @cdavm is working on integrating SNMP into nodewatcher for GSoC (to get data from Ubiquiti devices which do not have our agent running). So I am looking what would be the best plan to do so. I would love that we do not do same work in parallel so this is why I checked out this package again, because I remembered you were already working on it.

From what I see it does the basic thing: get the data. Probably we can just extend it as needed and then later on convert it to NetJSON or something.

**Comment by nemesisdesign** [comment]
Ok, up to you to decide. I can just tell you this is something I need both for ninux.org and for openwisp.org so I'm willing to put effort in helping and coordinating if needed.

**Comment by mitar** [comment]
Great! Good to know!

**Comment by johanovic** [comment]
Hi

The docs read:

> Status of this project
We are currently in 0.1 beta version.
The 0.1 final version will be out by April 2015.

Has that final version been released and are the docs not up to date or has the project stalled?

Thanks

**Comment by nemesisdesign** [comment]
@johanovic: the project has stalled unfortunately, it's still on my TODO list to use this code to implement some features in [openwisp2](https://github.com/openwisp/ansible-openwisp2), but I can't estimate when I will be able to do it.

**Comment by nemesisdesign** [comment]
We are giving another shot at this project, if anyone is interested in following updates, this is the place to look at: https://github.com/orgs/openwisp/projects/20.

We will focus exclusively on SNMP to make it more manageable.
